language: cpp
compiler: gcc
sudo: require
dist: xenial

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-xenial -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt510base qt510x11extras libgl1-mesa-dev libpoppler-qt5-dev libkf5solid-dev libmagic-dev # libffmpegthumnailer-dev
  - source /opt/qt*/bin/qt*-env.sh

script:
  - mkdir build && cd build/
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DQT5BUILD=ON
  - make -j$(nproc)
  - make DESTDIR=appdir -j$(nproc) install ; find appdir/
  - mkdir -p appdir/usr/share/icons/hicolor/128x128/apps/ # FIXME: CMake should do this
  - wget -c "https://github.com/probonopd/filer/blob/master/filer/icons/filer-128.png?raw=true" -O appdir/usr/share/icons/hicolor/128x128/apps/folder.png # FIXME
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  # export VERSION=... # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh D*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
